### ISSUE TITLE
HTTP Error 502.5

### ISSUE THREAD

**Issue by Patryks1337** [NickMaev/react-core-boilerplate#1]
When making a brand new project with this and after NPM INSTALL and NPM BUILD:DEV i get http ERROR 502.5 and cannot figure out why.

**Comment by NickMaev** [comment]
Do you have a skype or another tool to contact? Seems that reason on your side. Send me email or SMS.

**Comment by Patryks1337** [comment]
Thank you, It seemed as my runtime libaries where out of date :)
