### ISSUE TITLE
ASP.NET Core 3.0

### ISSUE THREAD

**Issue by ximxim** [NickMaev/react-core-boilerplate#10]
Awesome repo. Learned a lot from your code. Any chance you would be updating this repo to use ASP Core 3? I wonder what would change.

**Comment by NickMaev** [comment]
Hi, @ximxim 
Yes I will do it. 
But I think it will be also good to update the Bootstrap, isn't it?

**Comment by yumoraby** [comment]
@NickMaev new to React, would this project work with Identity scaffold item?

**Comment by NickMaev** [comment]
@yumoraby AFAIK it doesn't work with frameworks such as React, Angular

**Comment by yumoraby** [comment]
> @yumoraby AFAIK it doesn't work with frameworks such as React, Angular

Thanks looks like they are including it .net core 3 https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0

**Comment by NickMaev** [comment]
> > @yumoraby AFAIK it doesn't work with frameworks such as React, Angular
> 
> Thanks looks like they are including it .net core 3 https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0

There's no mention of any scaffolding in SPA 😔

**Comment by cedrox** [comment]
Hello @NickMaev, Thanks for the great work and for the share. 
+ 1 for this feature request :)

**Comment by JordanBrobyn** [comment]
Any progress towards moving to 3.0 or 3.1 here?

**Comment by NickMaev** [comment]
> Any progress towards moving to 3.0 or 3.1 here?

Working on it. Stay tuned!

**Comment by JordanBrobyn** [comment]
> > Any progress towards moving to 3.0 or 3.1 here?
> 
> Working on it. Stay tuned!

Much appreciated, I ended up upgrading myself but boy did I find a bunch of bugs moving from 2.2 Entity framework to 3.1 in my variation of your template. Not fun. Excited to see what you put together.

Thanks for your work.

**Comment by NickMaev** [comment]
> > > Any progress towards moving to 3.0 or 3.1 here?
> > 
> > 
> > Working on it. Stay tuned!
> 
> Much appreciated, I ended up upgrading myself but boy did I find a bunch of bugs moving from 2.2 Entity framework to 3.1 in my variation of your template. Not fun. Excited to see what you put together.
> 
> Thanks for your work.

Are you sure? My template doesn't contain 
any code with Entity Framework.

**Comment by JordanBrobyn** [comment]
> > > > Any progress towards moving to 3.0 or 3.1 here?
> > > 
> > > 
> > > Working on it. Stay tuned!
> > 
> > 
> > Much appreciated, I ended up upgrading myself but boy did I find a bunch of bugs moving from 2.2 Entity framework to 3.1 in my variation of your template. Not fun. Excited to see what you put together.
> > Thanks for your work.
> 
> Are you sure? My template doesn't contain
> any code with Entity Framework.

Yes sorry, I built off of your project and included a few other things like Entity framework. Some issues I had while upgrading were changing the routing to use Spa still and having the page route properly when not landing on home. A few features were depricated from 2.2 to 3.1 which were in use from the original template. The rest of the issues were around Entity Framework migrations.

**Comment by NickMaev** [comment]
Hello everyone! Happy New Year!
I've ported RCB to net.core 3.1 and Bootstrap 4.
Many improvements and awesome professional tools for boosting your development were also included.
I need to make the JavaScript version and some tests.
VSIX packages will be separated into Typescript and JavaScript versions.
Stay tuned!

**Comment by fcustodiosilva** [comment]
Hello,

Any news about the implementation?

Thanks for your work.

**Comment by NickMaev** [comment]
@fcustodiosilva 

I've been very busy these days. Still trying to find time for it.

RCB will be published this month, I think.

Thanks for waiting!

**Comment by NickMaev** [comment]
**React Core Boilerplate** was updated to .NET Core 3.1
