### ISSUE TITLE
Module not found: Can't resolve 'react-dom' in '<local dir>\node_modules\react-transition-group'

### ISSUE THREAD

**Issue by mikefili** [NickMaev/react-core-boilerplate#11]
I'm attempting to import react libraries into my application on this boilerplate template but receiving the following errors:

[Errors](https://ibb.co/cr5mJPd)

This is preventing me from being able to utilize libraries in the react front-end, which has been a big issue for me. Any suggestions?

**Comment by NickMaev** [comment]
Need more info
1. file which occurs errors above
2. package.json
3. webpack configs
