### ISSUE TITLE
Hot update fails after refresh

### ISSUE THREAD

**Issue by snzali** [NickMaev/react-core-boilerplate#12]
Hey Guys,
I have an issue with this template, and i am a little bit advanced on .Net Core, but this is my first time with a React/WebPack/Typescript project.
The issue is this:  Everytime i launch the project, or when i make an update in the tsx component, my main page looks like this : 
![image](https://user-images.githubusercontent.com/13869224/63346719-e7cb2f00-c355-11e9-8c95-e810f79099bd.png)
And, after everytime i hit F5, this is what it looks like : 
![image (1)](https://user-images.githubusercontent.com/13869224/63346775-03363a00-c356-11e9-95e1-e30001643c11.png)
After some debug sessions, i noticed that the only difference i have, is that in both cases every files are loaded, but in case i just update a tsx file, i have a new main-client.[id generated].hot-update.js loaded in the website:
![image (2)](https://user-images.githubusercontent.com/13869224/63347139-d0407600-c356-11e9-9090-0d501f0393ed.png)
I don't know if it is related, but the main fact is that, everytime i hit F5 in my website, it does'nt behave like a hot update, can you tell me how to set this ?
Thanks a lot,

**Comment by NickMaev** [comment]
Hello @snzali 

I have no information about your code which was affected.

But it seems there might be some problems connected to peculiarities of working with WebPack's HMR plugin. 

Check for requirements for the disposal logic in your scripts in [this article].(https://www.nativescript.org/blog/deep-dive-into-hot-module-replacement-with-webpack-part-two-handling-updates)
