### ISSUE TITLE
Unused parameters

### ISSUE THREAD

**Issue by kevingy** [NickMaev/react-core-boilerplate#16]
These two methods have unused parameters:

https://github.com/NickMaev/react-core-boilerplate/blob/9671f662882db9326dc69e56e9a095821fcca256/RCB.JavaScript/Extensions/ServiceCollectionExtensions.cs#L74

https://github.com/NickMaev/react-core-boilerplate/blob/9671f662882db9326dc69e56e9a095821fcca256/RCB.JavaScript/Extensions/ServiceCollectionExtensions.cs#L127

Are the parameters needed? FxCop is complaining that these parameters should either be removed or used in the method body.

**Comment by NickMaev** [comment]
Noted. Thank you.
