### ISSUE TITLE
Deployment Azure gives HTTP 500 Error

### ISSUE THREAD

**Issue by Jempan** [NickMaev/react-core-boilerplate#2]
First of all many thanks for a great starter template, it's exactly what I was looking for!

You don't happen to know how to deploy this web app to a cloud provider? I am using Visual Studio 2017 publish feature to push the code to an Azure Web App but I cannot get it to work :( The login page won't load and I get an HTTP 500 error. Pointing the browser to /api/person gives me the person data back so the app is apparently running. Done a lot of googling but it's very difficult to find any info on how to correctly deploy an SSR web app to Azure.

**Comment by NickMaev** [comment]
Hello, Jempan.
I'm glad to hear that.
My skype is **trix.mnr**
Please write me.

Solution of this issue will be published here.

**Comment by Jempan** [comment]
Hi again Nick and thanks for your quick reply! Tested to deploy the new boilerplate and got attached logged errors. Realized that it´s time to start to use Docker and Azure Kubernetes Service for my new project so hopefully, that will work better. You can close this issue if you want since it is more of an Azure problem than a problem with this boilerplate. 
[log.txt](https://github.com/NickMaev/react-core-boilerplate/files/2501900/log.txt)

**Comment by NickMaev** [comment]
Hello, Jenny! You are welcome.
First of all try to check the Node.js version. It must be >=9.5.0
OR
Set the "WEBSITE_NODE_DEFAULT_VERSION" to 6.11.2 (of doesn't work, try 9.5.0) in the "app settings" in Azure:
![](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/media/move-o365api-project-from-dev-to-prod/move-o365api-project-from-dev-to-prod-02.png)

**Comment by Jempan** [comment]
Thank you very much, version 6.11.2 works perfectly 🥇
