### ISSUE TITLE
Error Cannot find module 'rimraf'	React Core Boilerplate

### ISSUE THREAD

**Issue by ghost** [NickMaev/react-core-boilerplate#26]
I got this error after I built the app. Cannot find module 'rimraf'

For the benefit of others, this fixed it.

npm cache clean --force
npm install --force rimraf
npm install --force fs-extra

**Comment by arminhus** [comment]
Thanks so much this helped me out!!

**Comment by sztepen** [comment]
should anyone have problems with gyp, set the npm python version to for example, 2.7, like this:
npm config set python python2.7

see here also: https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules
