### ISSUE TITLE
Error: pngquant failed to build, make sure that libpng-dev is installed (Win10)

### ISSUE THREAD

**Issue by ReyOrtiz** [NickMaev/react-core-boilerplate#3]
Getting this error when doing `npm install` in Windows 10

```
‼ Command failed: C:\projects\react-core-boilerplate-master\ReactCoreBoilerplate\node_modules\pngquant-bin\vendor\pngquant.exe --version


  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (C:\projects\react-core-boilerplate-master\ReactCoreBoilerplate\node_modules\execa\index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm WARN fork-ts-checker-webpack-plugin@0.5.2 requires a peer of tslint@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-router-config@4.4.0-beta.6 requires a peer of react-router@4.4.0-beta.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@5.0.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@5.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<username>\AppData\Roaming\npm-cache\_logs\2019-03-02T16_54_05_901Z-debug.log
```

**Comment by NickMaev** [comment]
I think that the problem was in floating dependencies of the package `image-webpack-loader`. Is it ok now?

**Comment by gunnarsireus** [comment]
I have the same problem when downloading and building the project in Visual Studio:
  Built at: 2019-03-19 12:27:05
             Asset     Size       Chunks                    Chunk Names
    main-server.js  648 KiB  main-server  [emitted]  [big]  main-server
    Entrypoint main-server [big] = main-server.js

    ERROR in ./ClientApp/images/logo.png
    Module build failed (from ./node_modules/image-webpack-loader/index.js):
    Error: 'C:\Users\gunna\source\repos\ReactCoreBoilerplate\ReactCoreBoilerplate\node_modules\pngquant-bin\vendor\pngquant.exe' is not recognized as an internal or external command,
    operable program or batch file.

        at WriteWrap.afterWrite [as oncomplete] (net.js:779:14)
     @ ./ClientApp/pages/HomePage.tsx 1:486-521 1:904-908
     @ ./ClientApp/routes.tsx
     @ ./ClientApp/boot-server.tsx
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! webapp@0.0.0 build:dev: `node ./node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js && node ./node_modules/webpack/bin/webpack.js --config webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the webapp@0.0.0 build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gunna\AppData\Roaming\npm-cache\_logs\2019-03-19T11_27_06_171Z-debug.log

**Comment by NickMaev** [comment]
Package `image-webpack-loader` has been removed due to instability.
