### ISSUE TITLE
Add Person results in: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by gunnarsireus** [NickMaev/react-core-boilerplate#4]
react-dom.development.js:20065 Download the React DevTools for a better development experience: https://fb.me/react-devtools
client.js:92 [HMR] connected
react-dom.development.js:17461 Uncaught RangeError: Maximum call stack size exceeded
    at objEquiv (index.js:43)
    at module.exports (index.js:26)
    at objEquiv (index.js:91)
    at module.exports (index.js:26)
    at objEquiv (index.js:91)
    at module.exports (index.js:26)
    at objEquiv (index.js:91)
    at module.exports (index.js:26)
    at objEquiv (index.js:91)
    at module.exports (index.js:26)
rethrowOriginalError @ react-dom.development.js:17461
performUnitOfWork @ react-dom.development.js:18169
workLoop @ react-dom.development.js:18190
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
replayUnitOfWork @ react-dom.development.js:17437
renderRoot @ react-dom.development.js:18309
performWorkOnRoot @ react-dom.development.js:19165
performWork @ react-dom.development.js:19077
performSyncWork @ react-dom.development.js:19051
interactiveUpdates$1 @ react-dom.development.js:19320
interactiveUpdates @ react-dom.development.js:2169
dispatchInteractiveEvent @ react-dom.development.js:4880
react-dom.development.js:16013 The above error occurred in the <HelmetWrapper> component:
    in HelmetWrapper (created by ExamplePage)
    in div (created by ExamplePage)
    in ExamplePage (created by Context.Consumer)
    in Connect(ExamplePage) (created by Route)
    in Route (created by withRouter(Connect(ExamplePage)))
    in withRouter(Connect(ExamplePage)) (created by Route)
    in div (created by AuthorizedLayout)
    in div (created by AuthorizedLayout)
    in AuthorizedLayout (created by Route)
    in Route (created by AppRoute)
    in AppRoute
    in Switch
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Context.Consumer)
    in Connect(ConnectedRouterWithContext)
    in Provider
    in AppContainer

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
logCapturedError @ react-dom.development.js:16013
logError @ react-dom.development.js:16049
callback @ react-dom.development.js:16979
callCallback @ react-dom.development.js:11312
commitUpdateEffects @ react-dom.development.js:11351
commitUpdateQueue @ react-dom.development.js:11342
commitLifeCycles @ react-dom.development.js:16257
commitAllLifeCycles @ react-dom.development.js:17592
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:17788
completeRoot @ react-dom.development.js:19240
performWorkOnRoot @ react-dom.development.js:19169
performWork @ react-dom.development.js:19077
performSyncWork @ react-dom.development.js:19051
interactiveUpdates$1 @ react-dom.development.js:19320
interactiveUpdates @ react-dom.development.js:2169
dispatchInteractiveEvent @ react-dom.development.js:4880
react-hot-loader.development.js:285 RangeError: Maximum call stack size exceeded
    at objEquiv (index.js:43)
    at module.exports (index.js:26)
    at objEquiv (index.js:91)
    at module.exports (index.js:26)
    at objEquiv (index.js:91)
    at module.exports (index.js:26)
    at objEquiv (index.js:91)
    at module.exports (index.js:26)
    at objEquiv (index.js:91)
    at module.exports (index.js:26)
error @ react-hot-loader.development.js:285
componentDidCatch @ react-hot-loader.development.js:1319
callback @ react-dom.development.js:16980
callCallback @ react-dom.development.js:11312
commitUpdateEffects @ react-dom.development.js:11351
commitUpdateQueue @ react-dom.development.js:11342
commitLifeCycles @ react-dom.development.js:16257
commitAllLifeCycles @ react-dom.development.js:17592
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:17788
completeRoot @ react-dom.development.js:19240
performWorkOnRoot @ react-dom.development.js:19169
performWork @ react-dom.development.js:19077
performSyncWork @ react-dom.development.js:19051
interactiveUpdates$1 @ react-dom.development.js:19320
interactiveUpdates @ react-dom.development.js:2169
dispatchInteractiveEvent @ react-dom.development.js:4880
react-dom.development.js:506 Warning: AppContainer: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
warningWithoutStack @ react-dom.development.js:506
callback @ react-dom.development.js:16988
callCallback @ react-dom.development.js:11312
commitUpdateEffects @ react-dom.development.js:11351
commitUpdateQueue @ react-dom.development.js:11342
commitLifeCycles @ react-dom.development.js:16257
commitAllLifeCycles @ react-dom.development.js:17592
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:17788
completeRoot @ react-dom.development.js:19240
performWorkOnRoot @ react-dom.development.js:19169
performWork @ react-dom.development.js:19077
performSyncWork @ react-dom.development.js:19051
interactiveUpdates$1 @ react-dom.development.js:19320
interactiveUpdates @ react-dom.development.js:2169
dispatchInteractiveEvent @ react-dom.development.js:4880
ExamplePage.tsx:21 Uncaught (in promise) TypeError: Cannot read property 'setLastPage' of null
    at ExamplePage.eval (ExamplePage.tsx:21)
    at step (ExamplePage.tsx:20)
    at Object.eval [as next] (ExamplePage.tsx:20)
    at fulfilled (ExamplePage.tsx:20)
(anonymous) @ ExamplePage.tsx:21
step @ ExamplePage.tsx:20
(anonymous) @ ExamplePage.tsx:20
fulfilled @ ExamplePage.tsx:20
Promise.then (async)
step @ ExamplePage.tsx:20
(anonymous) @ ExamplePage.tsx:20
__awaiter @ ExamplePage.tsx:20
ExamplePage.onClickPersonEditorAdd__saveBtn @ ExamplePage.tsx:20
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:270
executeDispatch @ react-dom.development.js:561
executeDispatchesInOrder @ react-dom.development.js:583
executeDispatchesAndRelease @ react-dom.development.js:680
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:688
forEachAccumulated @ react-dom.development.js:662
runEventsInBatch @ react-dom.development.js:816
runExtractedEventsInBatch @ react-dom.development.js:824
handleTopLevel @ react-dom.development.js:4824
batchedUpdates$1 @ react-dom.development.js:19260
batchedUpdates @ react-dom.development.js:2150
dispatchEvent @ react-dom.development.js:4903
interactiveUpdates$1 @ react-dom.development.js:19315
interactiveUpdates @ react-dom.development.js:2169
dispatchInteractiveEvent @ react-dom.development.js:4880

**Comment by NickMaev** [comment]
Is it ok now?

**Comment by gunnarsireus** [comment]
Yes it works perfectly now!
