### ISSUE TITLE
Set "ASPNETCORE_ENVIRONMENT": "Production", => site.css not created, file missing error 

### ISSUE THREAD

**Issue by gunnarsireus** [NickMaev/react-core-boilerplate#5]
site.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
react-dom.development.js:20065 Download the React DevTools for a better development experience: https://fb.me/react-devtools
2(index):1 EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.
site.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
(index):1 EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.

**Comment by NickMaev** [comment]
Hello @gunnarsireus,
Thanks for using React Core Boilerplate!
I did a lot of bugfixes in new version. Is it ok now?

**Comment by NickMaev** [comment]
See #4
