### ISSUE TITLE
Publishing to Azure - TypeError: Cannot read property 'minify' of undefined

### ISSUE THREAD

**Issue by sverheggen** [NickMaev/react-core-boilerplate#7]
When I try to publish to azure I get the following error ERROR in vendor.js from Terser
TypeError: Cannot read property 'minify' of undefined
at minify (C:\Development\Azure\Azure Developer Course\Functions\TodoRestApi\TodoWebSiteReact\node_modules\terser-webpack-plugin\dist\minify.js:175:23) on command node node_modules/webpack/bin/webpack.js --env.prod

**Comment by NickMaev** [comment]
Hello @sverheggen,
Thanks for using React Core Boilerplate!
Please, try to update it to v. 1.6.2. It should work properly now.

**Comment by sverheggen** [comment]
Thanks for the fast reply. How can I upgrade to the 1.6.2. In Visual Studio it doesn't see this version. How can I update the boillerplate on the existing project? 
Thanks in advanced for help. 
Regards,
Stefan

**Comment by NickMaev** [comment]
Hello @sverheggen,
As opportunity you can override `package.json` file from this repository. I think it may solve your issue.

**Comment by NickMaev** [comment]
Hello @sverheggen,

To solve your issue try to call `npm install terser@3.16.1 -- save-dev` in the project's dir.

To update an extension in the Visual Studio: 
1. Go to `Extensions`, find the `React Core Boilerplate`.
2. Click on `Update` button.
OR
1. Go to the [marketplace](https://marketplace.visualstudio.com/items?itemName=NikolayMaev.ReactCoreBoilerplate).
2. Download and install the `.vsix` file.

Best regards,
Nick

**Comment by NickMaev** [comment]
Hello @sverheggen
Is it ok now?

**Comment by sverheggen** [comment]
Hi Nick,

Yes that is working now. Only I needed to start a new project with the latest version of the template. 

Thanks for your help. 

Regards,

Stefan
