### ISSUE TITLE
Feature Request: Allow developer to use JavaScript or TypeScript

### ISSUE THREAD

**Issue by tylerbhughes** [NickMaev/react-core-boilerplate#8]
I know I'm not alone in this when I say that I'm a JavaScript developer that has never touched TypeScript. It would be great if there was a way to allow the developer to use JavaScript instead of TypeScript. 

Additionally in previous versions of Visual Studio (if I remember correctly) Microsoft allowed for extensions to extend the One ASP.NET dialog to provide your own options when creating a new project. I'm not sure if this changed with recent versions of Visual Studio but it would be great if when selecting the project type if the developer could choose between JavaScript and TypeScript.

**Comment by NickMaev** [comment]
Hello @tylerbhughes 
Thanks for your request. That's a nice idea. 
Well, I will think about that in my spare time.

**Comment by NickMaev** [comment]
[JavaScript](https://github.com/NickMaev/react-core-boilerplate/tree/master/RCB.JavaScript) version of the React Core Boilerplate is successfully ported.
